[buildPlans.iosevka-flat]
family  = "Iosevka Flat"
spacing = "normal"
serifs  = "sans"
no-cv-ss = true

[buildPlans.iosevka-flat.variants.design]
capital-j = "flat-hook-serifed"
f = "flat-hook"
g = "single-storey-flat-hook"
j = "flat-hook-serifed"
k = "straight"
t = "flat-hook"
y = "straight-turn"
asterisk = "penta-low"

[buildPlans.iosevka-flat-term]
family  = "Iosevka Flat Term"
spacing = "term"
serifs  = "sans"
no-cv-ss = true

[buildPlans.iosevka-flat-term.variants.design]
capital-j = "flat-hook-serifed"
f = "flat-hook"
g = "single-storey-flat-hook"
j = "flat-hook-serifed"
k = "straight"
t = "flat-hook"
y = "straight-turn"
asterisk = "penta-low"

[buildPlans.iosevka-flat-fixed]
family  = "Iosevka Flat Fixed"
spacing = "fixed"
serifs  = "sans"
no-cv-ss = true

[buildPlans.iosevka-flat-fixed.variants.design]
capital-j = "flat-hook-serifed"
f = "flat-hook"
g = "single-storey-flat-hook"
j = "flat-hook-serifed"
k = "straight"
t = "flat-hook"
y = "straight-turn"
asterisk = "penta-low"

[buildPlans.iosevka-flat-proportional]
family = "Iosevka Flat Proportional"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-flat-proportional.variants.design]
capital-j = "flat-hook-serifed"
f = "flat-hook"
g = "single-storey-flat-hook"
j = "flat-hook-serifed"
k = "straight"
t = "flat-hook"
y = "straight-turn"
asterisk = "penta-low"

[collectPlans.iosevka-flat]
from = ["iosevka-flat", "iosevka-flat-term", "iosevka-flat-fixed", "iosevka-flat-proportional"]

[buildPlans.iosevka-hyperlegible]
family  = "Iosevka Hyperlegible"
spacing = "normal"
serifs  = "sans"
no-cv-ss = true

[buildPlans.iosevka-hyperlegible.variants.design]
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-e = "standard"
capital-f = "standard"
capital-g = "toothed-serifless-hooked"
capital-h = "standard"
capital-i = "serifed"
capital-j = "serifless"
capital-k = "straight"
capital-l = "standard"
capital-m = "flat-bottom"
capital-n = "standard"
capital-p = "closed"
capital-q = "crossing"
capital-r = "straight"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded"
capital-v = "straight"
capital-w = "straight-flat-top"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey"
b = "toothed"
c = "serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook"
g = "single-storey"
h = "straight"
i = "hooky"
j = "flat-hook-serifless"
k = "straight"
l = "flat-tailed"
m = "normal"
n = "straight"
p = "eared"
q = "tailed"
r = "compact"
s = "serifless"
t = "flat-hook"
u = "toothed"
v = "straight"
w = "straight-flat-top"
x = "straight-serifless"
y = "straight-turn"
z = "straight-serifless"
long-s = "flat-hook"
eszet = "sulzbacher"
turn-v = "straight"
lower-alpha = "crossing"
capital-gamma = "standard"
latn-epsilon = "serifless"
latn-reverse-epsilon = "serifless"
lower-iota = "flat-tailed"
lower-lambda = "straight-turn"
cyrl-ka = "straight"
cyrl-capital-u = "straight-turn"
zero = "reverse-slashed-oval"
one = "nobase-flat-top-serif"
two = "straight-neck"
four = "closed"
five = "oblique-upper-left-bar"
six = "closed-contour"
seven = "straight-serifless"
eight = "two-circles"
nine = "straight-bar"
tilde = "low"
asterisk = "penta-low"
underscore = "high"
paragraph-sign = "low"
caret = "medium"
paren = "normal"
brace = "curly"
number-sign = "slanted"
ampersand = "closed"
at = "fourfold"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
lig-ltgteq = "flat"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"

[buildPlans.iosevka-hyperlegible-term]
family  = "Iosevka Hyperlegible Term"
spacing = "term"
serifs  = "sans"
no-cv-ss = true

[buildPlans.iosevka-hyperlegible-term.variants.design]
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-e = "standard"
capital-f = "standard"
capital-g = "toothed-serifless-hooked"
capital-h = "standard"
capital-i = "serifed"
capital-j = "serifless"
capital-k = "straight"
capital-l = "standard"
capital-m = "flat-bottom"
capital-n = "standard"
capital-p = "closed"
capital-q = "crossing"
capital-r = "straight"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded"
capital-v = "straight"
capital-w = "straight-flat-top"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey"
b = "toothed"
c = "serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook"
g = "single-storey"
h = "straight"
i = "hooky"
j = "flat-hook-serifless"
k = "straight"
l = "flat-tailed"
m = "normal"
n = "straight"
p = "eared"
q = "tailed"
r = "compact"
s = "serifless"
t = "flat-hook"
u = "toothed"
v = "straight"
w = "straight-flat-top"
x = "straight-serifless"
y = "straight-turn"
z = "straight-serifless"
long-s = "flat-hook"
eszet = "sulzbacher"
turn-v = "straight"
lower-alpha = "crossing"
capital-gamma = "standard"
latn-epsilon = "serifless"
latn-reverse-epsilon = "serifless"
lower-iota = "flat-tailed"
lower-lambda = "straight-turn"
cyrl-ka = "straight"
cyrl-capital-u = "straight-turn"
zero = "reverse-slashed-oval"
one = "nobase-flat-top-serif"
two = "straight-neck"
four = "closed"
five = "oblique-upper-left-bar"
six = "closed-contour"
seven = "straight-serifless"
eight = "two-circles"
nine = "straight-bar"
tilde = "low"
asterisk = "penta-low"
underscore = "high"
paragraph-sign = "low"
caret = "medium"
paren = "normal"
brace = "curly"
number-sign = "slanted"
ampersand = "closed"
at = "fourfold"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
lig-ltgteq = "flat"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"

[buildPlans.iosevka-hyperlegible-fixed]
family  = "Iosevka Hyperlegible Fixed"
spacing = "fixed"
serifs  = "sans"
no-cv-ss = true

[buildPlans.iosevka-hyperlegible-fixed.variants.design]
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-e = "standard"
capital-f = "standard"
capital-g = "toothed-serifless-hooked"
capital-h = "standard"
capital-i = "serifed"
capital-j = "serifless"
capital-k = "straight"
capital-l = "standard"
capital-m = "flat-bottom"
capital-n = "standard"
capital-p = "closed"
capital-q = "crossing"
capital-r = "straight"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded"
capital-v = "straight"
capital-w = "straight-flat-top"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey"
b = "toothed"
c = "serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook"
g = "single-storey"
h = "straight"
i = "hooky"
j = "flat-hook-serifless"
k = "straight"
l = "flat-tailed"
m = "normal"
n = "straight"
p = "eared"
q = "tailed"
r = "compact"
s = "serifless"
t = "flat-hook"
u = "toothed"
v = "straight"
w = "straight-flat-top"
x = "straight-serifless"
y = "straight-turn"
z = "straight-serifless"
long-s = "flat-hook"
eszet = "sulzbacher"
turn-v = "straight"
lower-alpha = "crossing"
capital-gamma = "standard"
latn-epsilon = "serifless"
latn-reverse-epsilon = "serifless"
lower-iota = "flat-tailed"
lower-lambda = "straight-turn"
cyrl-ka = "straight"
cyrl-capital-u = "straight-turn"
zero = "reverse-slashed-oval"
one = "nobase-flat-top-serif"
two = "straight-neck"
four = "closed"
five = "oblique-upper-left-bar"
six = "closed-contour"
seven = "straight-serifless"
eight = "two-circles"
nine = "straight-bar"
tilde = "low"
asterisk = "penta-low"
underscore = "high"
paragraph-sign = "low"
caret = "medium"
paren = "normal"
brace = "curly"
number-sign = "slanted"
ampersand = "closed"
at = "fourfold"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
lig-ltgteq = "flat"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"

[buildPlans.iosevka-hyperlegible-proportional]
family  = "Iosevka Hyperlegible Proportional"
spacing = "quasi-proportional"
serifs  = "sans"
no-cv-ss = true

[buildPlans.iosevka-hyperlegible-proportional.variants.design]
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-e = "standard"
capital-f = "standard"
capital-g = "toothed-serifless-hooked"
capital-h = "standard"
capital-i = "serifed"
capital-j = "serifless"
capital-k = "straight"
capital-l = "standard"
capital-m = "flat-bottom"
capital-n = "standard"
capital-p = "closed"
capital-q = "crossing"
capital-r = "straight"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded"
capital-v = "straight"
capital-w = "straight-flat-top"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey"
b = "toothed"
c = "serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook"
g = "single-storey"
h = "straight"
i = "hooky"
j = "flat-hook-serifless"
k = "straight"
l = "flat-tailed"
m = "normal"
n = "straight"
p = "eared"
q = "tailed"
r = "compact"
s = "serifless"
t = "flat-hook"
u = "toothed"
v = "straight"
w = "straight-flat-top"
x = "straight-serifless"
y = "straight-turn"
z = "straight-serifless"
long-s = "flat-hook"
eszet = "sulzbacher"
turn-v = "straight"
lower-alpha = "crossing"
capital-gamma = "standard"
latn-epsilon = "serifless"
latn-reverse-epsilon = "serifless"
lower-iota = "flat-tailed"
lower-lambda = "straight-turn"
cyrl-ka = "straight"
cyrl-capital-u = "straight-turn"
zero = "reverse-slashed-oval"
one = "nobase-flat-top-serif"
two = "straight-neck"
four = "closed"
five = "oblique-upper-left-bar"
six = "closed-contour"
seven = "straight-serifless"
eight = "two-circles"
nine = "straight-bar"
tilde = "low"
asterisk = "penta-low"
underscore = "high"
paragraph-sign = "low"
caret = "medium"
paren = "normal"
brace = "curly"
number-sign = "slanted"
ampersand = "closed"
at = "fourfold"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
lig-ltgteq = "flat"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"

[collectPlans.iosevka-hyperlegible]
from = ["iosevka-hyperlegible", "iosevka-hyperlegible-term", "iosevka-hyperlegible-fixed", "iosevka-hyperlegible-proportional"]
