[buildPlans.IosevkaJDK]
family         = "Iosevka JDK"
description    = "JDK Style"
snapshotFamily = "Iosevka JDK"

[buildPlans.IosevkaJDK.variants.design]
two                  = "straight-neck-serifless"
eight                = "two-circles"
zero                 = "oval-slashed"
capital-d            = "more-rounded-serifless"
capital-q            = "crossing"
f                    = "flat-hook-serifless"
g                    = "double-storey"
j                    = "flat-hook-serifed"
r                    = "hookless-serifed"
t                    = "flat-hook"
w                    = "straight-flat-top-serifless"
y                    = "straight-turn-serifless"
asterisk             = "penta-low"
at                   = "fourfold-solid-inner"
percent              = "dots"
lig-ltgteq           = "slanted"
lig-neq              = "slightly-slanted-dotted"
lig-plus-chain       = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"
